#!/usr/bin/env ruby

require 'commander/import'
require 'antenna'

program :name, 'Antenna'
program :version, Antenna::VERSION
program :description, 'Painless iOS over-the-air enterprise distribution'

program :help, 'Author', 'Joshua Bauer <josh@wurrly.com>'
program :help, 'Website', 'https://www.github.com/Wurrly/antenna'
program :help_formatter, :compact

# global_option('--verbose') { $verbose = true }

default_command :help

require 'antenna/commands'